apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-component
    app.kubernetes.io/part-of: test-app-167576634
  name: go-component
  namespace: zlap0abn-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: go-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: go-component
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:zlap0abn-tenant-go-component
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
