apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: test-app-167576634
    appstudio.openshift.io/component: java-quarkus
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: java-quarkus
  namespace: zlap0abn-tenant
spec:
  git_provider:
    secret:
      key: github.token
      name: pipelines-as-code-secret
    webhook_secret:
      key: https___github.com_dheerajodha_devfile-sample-code-with-quarkus
      name: pipelines-as-code-webhooks-secret
  url: https://github.com/dheerajodha/devfile-sample-code-with-quarkus
